// Generated by CoffeeScript 1.6.2
var domain;

domain = require('domain');

exports.requestContext = function(init, cleanup) {
  return function(req, res, next) {
    var _ref;

    domain = require('domain').active;
    if (domain == null) {
      throw new Error('no active domain');
    }
    if (typeof init !== 'function') {
      _ref = init, init = _ref.init, cleanup = _ref.cleanup;
    }
    domain.__context__ = req.__context__ = init();
    res.on('finish', function() {
      if ((cleanup != null) && (domain.__context__ != null)) {
        cleanup(domain.__context__);
      }
      return domain.__context__ = null;
    });
    return next();
  };
};

exports.requestContextOnError = function(cleanup) {
  return function(err, req, res, next) {
    if (typeof cleanup !== 'function') {
      cleanup = cleanup.cleanup;
    }
    if (cleanup != null) {
      cleanup(req.__context__);
    }
    domain.__context__ = req.__context__ = null;
    return next(err);
  };
};
